project:
  type: website
  output-dir: docs

website:
  title: "Christine Hedde-von Westernhagen"
  navbar:
    title: '<span style="font-size:12pt">Christine Hedde-von Westernhagen</span>'
    background: dark
    search: true
    right:
      - href: index.qmd
        text: Home
      - href: showcase.qmd
        text: Showcase
      - href: resources/cv_chw_acad.pdf
        text: CV
  page-footer: 
    left: '<span style="font-size:9pt">© 2024 Christie Hedde-von Westernhagen - Powered by Quarto</span>'

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    margin-top: 30px
